Update "broccoli-uglify-sourcemap" to v2.0.0-beta.1
ember-cli/ember-cli-uglify pull request #17
Opened 2017-07-09 17:15 UTC by Turbo87

related to https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/49

2017-07-09 17:35 UTC, rwjblue requested changes

2017-07-09 17:35 UTC, rwjblue commented on index.js
> +    const defaults = require('lodash.defaultsdeep');
This is not included in `package.json`

2017-07-09 18:08 UTC, Turbo87 commented on index.js
> +    const defaults = require('lodash.defaultsdeep');
whoops, fixed

2017-07-09 18:12 UTC, rwjblue approved these changes

2017-07-09 18:12 UTC, rwjblue requested changes

2017-07-09 18:12 UTC, rwjblue commented on package.json
> +    "lodash.defaultsdeep": "^4.6.0"
Wait, this should be a dep not a devDep

2017-07-09 18:26 UTC, Turbo87 commented on package.json
> +    "lodash.defaultsdeep": "^4.6.0"
I should go to bed... fixed

2017-07-10 06:32 UTC, Turbo87 commented
since the two comments are addressed I'm merging and releasing as beta too

2017-07-10 06:32 UTC, merged